version: '{build}'
image: Visual Studio 2019
configuration:
- Debug
- Release
before_build:
- ps: nuget restore ICSharpCode.SharpZipLib.sln
- ps: .\tools\appveyor-docfx-init.ps1
build_script:
- for /f "tokens=1,* delims=-" %%a in ('"git describe --tags --long"') do set version_suffix=%%b
- dotnet build ICSharpCode.SharpZipLib.sln --version-suffix "%version_suffix%-%CONFIGURATION%"
after_build:
- ps: .\tools\appveyor-docfx-build.ps1
test_script:
- ps: tools\appveyor-test.ps1
artifacts:
- path: ICSharpCode.SharpZipLib\bin\$(configuration)\*.nupkg
- path: docs\help\_site
  type: zip
  name: Documentation
